version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - UVICORN_APP=app.app:app
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=5000
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://backend:5000/api
    restart: unless-stopped

volumes:
  node_modules: